shell:
  program: /bin/zsh
  args:
    - --login
window:
  decorations: none
  startup_mode: Windowed
  opacity: 0.85
live_config_reload: true
colors:
  # Default colors
  primary:
    background: '#292C3E'
    foreground: '#EBEBEB'

  # Cursor colors
  cursor:
    text: '#FF261E'
    cursor: '#FF261E'

  # Normal colors
  normal:
    black: '#0d0d0d'
    red: '#FF301B'
    green: '#A0E521'
    yellow: '#FFC620'
    blue: '#1BA6FA'
    magenta: '#8763B8'
    cyan: '#21DEEF'
    white: '#EBEBEB'

  # Bright colors
  bright:
    black: '#6D7070'
    red: '#FF4352'
    green: '#B8E466'
    yellow: '#FFD750'
    blue: '#1BA6FA'
    magenta: '#A578EA'
    cyan: '#73FBF1'
    white: '#FEFEF8'
theme: Argonaut
font:
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
