memodir = "~/.memolist/memo"
editor = "vim"
column = 20
width = 0
selectcmd = "peco"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "~/.memolist/plugins"
templatedirfile = ""
templatebodyfile = ""
